;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Food.Burnt",NewTagName="Food.Uncooked")
+GameplayTagRedirects=(OldTagName="Food.Uncooked.Meat.Leviathan",NewTagName="Food.Uncooked.Meat.LeviathanSteak")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Food",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Meat",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Meat.TestMeat",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Misc",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Misc.TestMisc",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Veg",DevComment="")
+GameplayTagList=(Tag="Food.Burnt.Veg.TestVeg",DevComment="")
+GameplayTagList=(Tag="Food.Cooked",DevComment="")
+GameplayTagList=(Tag="Food.Cooked.Dish",DevComment="")
+GameplayTagList=(Tag="Food.Cooked.Dish.GlazedLeviathanSteak",DevComment="")
+GameplayTagList=(Tag="Food.Cooked.Dish.Mush",DevComment="")
+GameplayTagList=(Tag="Food.NULL",DevComment="")
+GameplayTagList=(Tag="Food.Uncooked",DevComment="")
+GameplayTagList=(Tag="Food.Uncooked.Meat",DevComment="")
+GameplayTagList=(Tag="Food.Uncooked.Meat.LeviathanSteak",DevComment="")
+GameplayTagList=(Tag="Food.Uncooked.Misc",DevComment="")
+GameplayTagList=(Tag="Food.Uncooked.Misc.Slime",DevComment="")

